// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnitnjwwldlujdjnnlvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaXRuand3bGRsdWpkam5ubHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5Mjg5MzIsImV4cCI6MjA0OTUwNDkzMn0.XHtMSqSUcxjDJly9aLTjbqbnZkkQoIRidJBT0-7vCP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);